fix converting NULL to uint64 is unsupported in size table
prometheus-community/postgres_exporter pull request #1070
Opened 2024-09-23 20:25 UTC by Electronn

This patch fixes bug of unwanted null in uint64 type. Bug causes errors on AWS Aurora PostgreSQL clusters:
```
Scan error on column index 1, name \"size\": converting NULL to uint64 is unsupported
```

2024-10-17 16:50 UTC, Sticksman approved these changes

2025-01-01 20:56 UTC, sysadmind requested changes

2025-01-01 20:56 UTC, sysadmind commented on collector/pg_wal.go
> +	var segmentsValue float64
segments should never be NULL. It's a `count(*)` which I don't believe can return a NULL value. The error you reported was on the size column. If Aurora is returning NULL for that column, I think there should not be a metric emitted from the exporter. I don't know what value a metric for WAL size with a value of 0 is.

2026-02-09 21:55 UTC, kingdruid commented on collector/pg_wal.go
> +	var segmentsValue float64
size is NULL because the number of segments is 0, since the `pg_ls_waldir()` function in AWS Aurora returns 0 rows. It looks like WAL is implemented differently in Aurora, so this metric does not really make sense there. Possibly a different metric is needed for Aurora.

2026-02-11 02:37 UTC, sysadmind commented on collector/pg_wal.go
> +	var segmentsValue float64
But the count(*) will still be 0 even with no rows right?

2026-08-25 12:34 UTC, ArthurSens commented
Hey, I'm closing this PR because there's been no activity for a long time. It would be awesome to have this fixed as part of the work @megative is doing to better support Aurora!

2026-08-25 12:34 UTC, closed without merging