feat: add support for pg_stat_user_indexes
prometheus-community/postgres_exporter pull request #1071
Opened 2024-10-04 13:58 UTC by michael-todorovic

This PR adds support for `pg_stat_user_indexes` in order to get scan, read, fetch statistics about indexes. This can be used to find out unused/low-used indexes

This relates to issue #1065

2024-10-11 09:43 UTC, michael-todorovic commented
You can identify unused indexes with this promql:
```
count((pg_stat_user_indexes_idx_scan_total{environment="production"} < 15)
* on (datname, environment, indexrelname, instance, job, relname, schemaname)
group_left(is_primary, is_unique, is_ready, is_valid)
(pg_index_properties{is_primary="0"} * on (datname, environment, indexrelname, instance, job, relname, schemaname)
  pg_index_size_bytes > 104857600)) by (instance, schemaname, relname, indexrelname)
```
It searches for production indexes scanned less than 15 times, which are not primary keys (you need to keep those indexes for PG itself) and that are bigger than 100MB

The metrics themselves look like: 
```
pg_stat_user_indexes_idx_scan_total{datname="my_db", environment="production", indexrelname="idx_name", instance="my_server", job="pg_exporter_preview", relname="my_table", schemaname="my_schema"} 0
pg_stat_user_indexes_idx_tup_fetch{datname="my_db", environment="production", indexrelname="idx_name", instance="my_server", job="pg_exporter_preview", relname="my_table", schemaname="my_schema"} 0
pg_stat_user_indexes_idx_tup_read{datname="my_db", environment="production", indexrelname="idx_name", instance="my_server", job="pg_exporter_preview", relname="my_table", schemaname="my_schema"} 0
pg_index_properties{datname="my_db", environment="production", indexrelname="idx_name", instance="my_server", is_primary="0", is_ready="1", is_unique="0", is_valid="1", job="pg_exporter_preview", relname="my_table", schemaname="my_schema"} 1
pg_index_size_bytes{datname="my_db", environment="production", indexrelname="idx_name", instance="my_server", job="pg_exporter_preview", relname="my_table", schemaname="my_schema"} 9654042624
```

2024-12-19 18:37 UTC, chris-downs commented
To give this a bump, we are now using this branch in production with no issues and it's very useful. It would be great to get it into mainline.

2024-12-22 20:49 UTC, sysadmind requested changes
In addition to the comments on the code, all of the dates for the Copyright need to be updated to the current year for the files that you have created. I think the guys are good here, my feedback is mostly about being able to maintain this code long term.

2024-12-22 20:49 UTC, sysadmind commented on collector/pg_index.go
> +	"log/slog"
I'm not sure why this import is in it's own section. This should go with the stdlib imports above.

2024-12-22 20:49 UTC, sysadmind commented on collector/pg_index.go
> +	return fmt.Sprintf("SELECT %s FROM pg_catalog.pg_stat_user_indexes s JOIN pg_catalog.pg_index i ON s.indexrelid = i.indexrelid WHERE i.indislive='1';", strings.Join(columns, ","))
We don't typically use a function to build the query unless we need dynamic columns. In this case it should just be a static query const.

2024-12-22 20:49 UTC, sysadmind commented on collector/pg_index.go
> +		r := []any{
I don't think that this slice adds anything. We can scan directly into the vars above.

2024-12-22 20:49 UTC, sysadmind commented on collector/pg_index.go
> +		datnameLabel := "unknown"
Do these metrics make sense when these values are not known? I feel that if too many are NULL/unknown, the metric is useless and should just be skipped.

2024-12-22 20:49 UTC, sysadmind commented on collector/pg_index.go
> +		sizeLabels := []string{datnameLabel, schemanameLabel, relnameLabel, indexrelnameLabel}
Again, what does the slice improve vs just using the values below?

2024-12-22 20:49 UTC, sysadmind commented on collector/pg_index.go
> +		propertiesLabels := []string{datnameLabel, schemanameLabel, relnameLabel, indexrelnameLabel, indexIsUniqueLabel, indexIsPrimaryLabel, indexIsValidLabel, indexIsReadyLabel}
Again, what does the slice improve vs just using the values below?

2026-06-19 13:02 UTC, brunomanzo commented
@sysadmind since this is stale,
 mind if i fix the comments and open a new PR so we can get this in? I really need this info exported

2026-06-19 17:59 UTC, ArthurSens commented
> @sysadmind since this is stale, mind if i fix the comments and open a new PR so we can get this in? I really need this info exported

sysadmind is out on parental leave for a while. I'd be happy to review your PR if you take this over @brunomanzo, but we'll have to wait for @sysadmind or @SuperQ for the merge

2026-09-11 19:06 UTC, ArthurSens commented
I'm closing this one due to inactivity. I'm happy to review a new PR if someone is still willing to contribute this change!

2026-09-11 19:06 UTC, closed without merging