Collect idle_in_transaction_time from PG >= 15
prometheus-community/postgres_exporter pull request #1075
Opened 2024-10-17 14:51 UTC by ajmaidak

idle_in_transaction_time was added to pg_stat_database in pg 15

https://www.postgresql.org/docs/15/monitoring-stats.html#MONITORING-PG-STAT-DATABASE-VIEW

2024-10-17 16:39 UTC, Sticksman approved these changes

2025-02-15 14:36 UTC, sysadmind requested changes

2025-02-15 14:36 UTC, sysadmind commented on collector/pg_stat_database.go
> +			continue
I don't think this needs to skip the whole row in this case. I think this logic can be to skip sending the metric to the channel down on line 540 instead. I know the logic above is this way, but I think technically this addition could break things for other users if this field is NULL, so I want to avoid that.

2026-06-29 10:47 UTC, kyrias commented
Any chance this PR will go anywhere at this point, or should I open a new one?

2026-06-29 12:57 UTC, ArthurSens commented
@kyrias feel free to open a new one. We've been waiting for the author for quite a while now

2026-09-10 13:38 UTC, ArthurSens commented
Taking the liberty to close this PR due to the amount of time without activity

2026-09-10 13:38 UTC, closed without merging