Gitlab Collector: Wal Receiver Collector and Test
prometheus-community/postgres_exporter pull request #844
Opened 2023-06-28 18:07 UTC by Sticksman

Split from #819

2023-06-29 00:57 UTC, sysadmind commented on collector/pg_stat_walreceiver.go
> +		case status
I'm not sure it makes sense to use such a CASE statement when the query is defined in code. We can do the translation here in the exporter in code. Not using CASE makes the query much easier to read.

2023-06-29 00:57 UTC, sysadmind commented on collector/pg_stat_walreceiver.go
> +		(flushed_lsn- '0/0') % (2^52)::bigint as flushed_lsn,
If this is the only field that is different between the two queries, I would prefer to use something like fmt.Sprintf to stick this into a single query. There's a lot here and any future changes would need to be careful to make the same change in both queries.

2023-06-29 00:57 UTC, sysadmind commented on collector/pg_stat_walreceiver.go
> +	for rows.Next() {
I don't think that the NULL values are useful to report as metrics.

2023-06-30 08:29 UTC, SuperQ requested changes

2023-06-30 08:29 UTC, SuperQ commented on collector/pg_stat_walreceiver.go
> +		var statusMetric float64
We don't do value-based status in Prometheus. The standard practice for this is to have these values be a label on an info metric with a constant value of `1`.

2023-06-30 08:29 UTC, SuperQ commented on collector/pg_stat_walreceiver.go
> +	)
```suggestion
	statWalReceiverStatus = prometheus.NewDesc(
		prometheus.BuildFQName(namespace, statWalReceiverSubsystem, "status_info"),
		"Activity status of the WAL receiver process",
		[]string{"upstream_host", "slot_name", "status"},
		prometheus.Labels{},
	)
```

2023-07-14 13:54 UTC, SuperQ commented on collector/pg_stat_walreceiver.go
> +			latestEndTimeMetric,
Minor nit, we don't need to do these assigns.

```suggestion
		ch <- prometheus.MustNewConstMetric(
			statWalReceiverLatestEndTime,
			prometheus.CounterValue,
			latestEndTime.Float64,
```

2023-07-14 16:29 UTC, Sticksman commented
Yeah I think it made a lot more sense when we were actually checking for null values, but now we can probably get rid of them

2023-07-14 16:34 UTC, Sticksman commented
Probably makes sense to do a cleanup PR when I'm done

2023-07-14 18:59 UTC, sysadmind approved these changes
Just one formatting request.

2023-07-14 18:59 UTC, sysadmind commented on collector/pg_stat_walreceiver.go
> +		%sreceive_start_tli,
```suggestion
		%s
receive_start_tli,
```
Not having whitespace here makes it hard to see this template variable. I think it's more important for the query to look easy to read here than it is after templating.

2023-07-21 18:42 UTC, merged

2023-09-21 05:12 UTC, dswarbrick commented
Tests fail on 32-bit platforms.
```
# github.com/prometheus-community/postgres_exporter/collector [github.com/prometheus-community/postgres_exporter/collector.test]
collector/pg_stat_walreceiver_test.go:67:4: cannot use 1200668684563608 (untyped int constant) as int value in argument to sqlmock.NewRows(columns).AddRow (overflows)
collector/pg_stat_walreceiver_test.go:69:4: cannot use 1200668684563609 (untyped int constant) as int value in argument to sqlmock.NewRows(columns).AddRow (overflows)
collector/pg_stat_walreceiver_test.go:73:4: cannot use 1200668684563610 (untyped int constant) as int value in argument to sqlmock.NewRows(columns).AddRow (overflows)
collector/pg_stat_walreceiver_test.go:146:4: cannot use 1200668684563608 (untyped int constant) as int value in argument to sqlmock.NewRows(columns).AddRow (overflows)
collector/pg_stat_walreceiver_test.go:151:4: cannot use 1200668684563610 (untyped int constant) as int value in argument to sqlmock.NewRows(columns).AddRow (overflows)
ok      github.com/prometheus-community/postgres_exporter/cmd/postgres_exporter 0.007s
FAIL    github.com/prometheus-community/postgres_exporter/collector [build failed]
ok      github.com/prometheus-community/postgres_exporter/config        0.005s
FAIL
```
This is yet another occasion where adding 32-bit testing (e.g. `GOARCH=386`) to CI would have caught this, a la #857.