stat_user_tables: Add total size metric
prometheus-community/postgres_exporter pull request #904
Opened 2023-09-08 19:30 UTC by divergentdave

This adds a new `pg_stat_user_tables_total_size` metric to the stat_user_tables collector. It uses the [`pg_total_relation_size()`](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-DBSIZE) function. (I had been using this via a modification to the query YAML file previously)

Note that #847 does something similar, but as a separate collector. This query is only scoped to user tables, not all relations.

2023-09-11 12:01 UTC, SuperQ requested changes
Minor nit, otherwise LGTM

2023-09-11 12:01 UTC, SuperQ commented on collector/pg_stat_user_tables.go
> +		prometheus.BuildFQName(namespace, userTableSubsystem, "total_size"),
```suggestion
		prometheus.BuildFQName(namespace, userTableSubsystem, "size_bytes"),
```

2023-09-11 16:50 UTC, Sticksman approved these changes

2023-09-11 16:51 UTC, Sticksman commented
LGTM

2023-09-12 11:46 UTC, SuperQ approved these changes

2023-09-12 13:07 UTC, sysadmind approved these changes
LGTM. I think in the future we need to come back and think about metrics when the column is NULL. I'm not sure this metric makes sense when the value exported is 0

2023-09-12 13:07 UTC, merged